package com.model;
// Generated 22 sep. 2019 11:31:57 by Hibernate Tools 4.3.1



/**
 * Producto generated by hbm2java
 */
public class Producto  implements java.io.Serializable {


     private int codigoProducto;
     private Proveedor proveedor;
     private String nombre;
     private String categoria;
     private Double precio;
     private Integer anioFabricacion;
     private Integer anioVencimiento;

    public Producto() {
    }

	
    public Producto(int codigoProducto) {
        this.codigoProducto = codigoProducto;
    }
    public Producto(int codigoProducto, Proveedor proveedor, String nombre, String categoria, Double precio, Integer anioFabricacion, Integer anioVencimiento) {
       this.codigoProducto = codigoProducto;
       this.proveedor = proveedor;
       this.nombre = nombre;
       this.categoria = categoria;
       this.precio = precio;
       this.anioFabricacion = anioFabricacion;
       this.anioVencimiento = anioVencimiento;
    }
   
    public int getCodigoProducto() {
        return this.codigoProducto;
    }
    
    public void setCodigoProducto(int codigoProducto) {
        this.codigoProducto = codigoProducto;
    }
    public Proveedor getProveedor() {
        return this.proveedor;
    }
    
    public void setProveedor(Proveedor proveedor) {
        this.proveedor = proveedor;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getCategoria() {
        return this.categoria;
    }
    
    public void setCategoria(String categoria) {
        this.categoria = categoria;
    }
    public Double getPrecio() {
        return this.precio;
    }
    
    public void setPrecio(Double precio) {
        this.precio = precio;
    }
    public Integer getAnioFabricacion() {
        return this.anioFabricacion;
    }
    
    public void setAnioFabricacion(Integer anioFabricacion) {
        this.anioFabricacion = anioFabricacion;
    }
    public Integer getAnioVencimiento() {
        return this.anioVencimiento;
    }
    
    public void setAnioVencimiento(Integer anioVencimiento) {
        this.anioVencimiento = anioVencimiento;
    }




}


