package com.model;
// Generated 22 sep. 2019 11:31:57 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Proveedor generated by hbm2java
 */
public class Proveedor  implements java.io.Serializable {


     private int codigoProveedor;
     private String nombre;
     private String direccion;
     private String telefono;
     private Set productos = new HashSet(0);

    public Proveedor() {
    }

	
    public Proveedor(int codigoProveedor) {
        this.codigoProveedor = codigoProveedor;
    }
    public Proveedor(int codigoProveedor, String nombre, String direccion, String telefono, Set productos) {
       this.codigoProveedor = codigoProveedor;
       this.nombre = nombre;
       this.direccion = direccion;
       this.telefono = telefono;
       this.productos = productos;
    }
   
    public int getCodigoProveedor() {
        return this.codigoProveedor;
    }
    
    public void setCodigoProveedor(int codigoProveedor) {
        this.codigoProveedor = codigoProveedor;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getDireccion() {
        return this.direccion;
    }
    
    public void setDireccion(String direccion) {
        this.direccion = direccion;
    }
    public String getTelefono() {
        return this.telefono;
    }
    
    public void setTelefono(String telefono) {
        this.telefono = telefono;
    }
    public Set getProductos() {
        return this.productos;
    }
    
    public void setProductos(Set productos) {
        this.productos = productos;
    }




}


